config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'etic/home'
  get 'etic/material'
  get 'etic/kataskevastes'
  get 'etic/system'
  get 'etic/line'
  get 'etic/leaf'
  get 'etic/open_type'
  get 'etic/color'
  get 'etic/corol_kasas'
  get 'etic/color_fulou'
  get 'etic/diastaseis'
  get 'etic/extra'
  get 'etic/profil'
  get 'etic/tzamia'
  get 'etic/epikathimena'
  get 'etic/color_epikathimenou'
  get 'etic/color_eksoterikou'
  get 'etic/eksoterika'
  get 'etic/color_persidas'
  get 'etic/upologismos'
  get 'etic/typos'
  get 'etic/color_typos'
  get 'etic/color_odoigou'
  get 'etic/color_profil'
  get 'etic/profil'
  get 'etic/upologismos_platos_profil'
  get 'etic/upologismos_upsos_profil'
  get 'etic/color_epistrofi'
  get 'etic/price'
  get 'etic/card'
  get 'etic/pdf'
  get 'etic/export'
  delete 'etic/destroy'
  put 'etic/update'
  get 'etic/diagrafi'
  get 'etic/prosthiki_sto_kalathi'
  get 'etic/etic_card'
  get 'etic/etic_user_card'
  get 'etic/etic_pse_user_card'
  get 'etic/new_user'
  get 'etic/add_user'
  get 'etic/diagrafi_admin'
  get 'etic/update_admin'
  get 'etic/export_admin'
  get 'etic/pdf_admin'
  get 'etic/pse_done'
  get 'etic/contact'
  get 'etic/send_mail'
  get 'etic/pse_user'
  get 'etic/user_diax'
  get 'etic/simple_user_cr'
  get 'etic/add_simple_user'
  get 'etic/simple_pse_user_card'
  get 'etic/oloklirwsi_simple_user_pses'
  get 'etic/simple_pse_user'
  get 'etic/diagrafi_simple_user'
  get 'etic/pdf_simple_user'
  get 'etic/export_simple_user'
  post 'etic/save_image'
  get 'etic/select_customer'
  get 'etic/new_offer'
  get 'etic/import_terms'
  get 'etic/import_sungate'
  get 'etic/history'
  get 'etic/history_admin'
  get 'etic/language'
  devise_scope :user do
    root :to => 'devise/sessions#new'
  end

end

app/controllers/etic_controller.rb
class EticController < ApplicationController

    ## Kati gia session
	skip_before_filter :verify_authenticity_token, :only => [:update]

    ## Για καθε url που παταω με το χερι, δεν πηγενει το site γιατι πρεπει πρωτα να κανεις log in.
    ## Εκτος αν αλλαξω γλωσσα που γίνεται και στην αρχικη σελιδα του log in.
	before_action :authenticate_user!, except: [:language, :contact, :send_mail]

	layout "app", :only => [:home, :material, :leaf, :open_type, :color, :diastaseis, :extra]

    ## Αλλαγη γλωσσας. Γενικα εχω ένα session[:locale] απο το application_controller.
    ## Αν αλλαξει η γλωσσα την αλλαζω με τα if. 
	def language
	  if ( params[:lang] == "en" )
	    I18n.locale = 'en'
	    session[:locale] = "en"
	  end
	  if ( params[:lang] == "gr" )
	    I18n.locale = 'gr'
	    session[:locale] = "gr"
	  end
	  if ( params[:lang] == "de" )
	    I18n.locale = 'de'
	    session[:locale] = "de"
	  end
	  I18n.locale = session[:locale]
	  if current_user
	  	redirect_to :back
	  else
	  	redirect_to root_path
	  end
	end

    ## CONTACT: Η σελίδα που βλέπω όταν πατάω contact στην μπαρα
    ## SEND_MAIL: Η μέθοδος που στέλνει mail στον admin. UserMailer -> class, welcome_email -> method
	def contact
	end

	def send_mail
		user_info = {:email_user => params[:email], :username => params[:onoma], :number => params[:arithmos], :message => params[:koimeno], :aiteria => params[:company], :epitheto => params[:surname]} 
        UserMailer.welcome_email(user_info).deliver #this will deliver the mail
        #redirect_to root_path, alert: "Watch it, mister!"
	end

    ## Μέθοδος που καλείτε απο το view etic_card όταν παταω + σε κουφωμα για νέο χρήστη.
    ## Κραταει το id του pseudo user που πατησα + σε καθοληκή μεταβλητή $pseUserId  
	def pse_user
		#$pseUserId = params[:pse_user]
		session[:pseUserId] = params[:pse_user]
		redirect_to etic_home_path 
	end

	def simple_pse_user
		#$pseUserId_2 = params[:pse_user]
		#$paraggelia_simple = params[:paraggelia_id]
		session[:paraggelia_simple] = params[:paraggelia_id] #To id της παραγγελίας
		session[:pseUserId] = params[:pse_user] #Το id αν ειμαι με admin για τους user του admin
		session[:dealer_id] = params[:admin] #Το id του dealer αν κανει + ο admin σε παραγγελία
		redirect_to etic_home_path
	end

    ## Αρχική σελίδα μετα το log in. 
    ## Παραθέτω ολα τα ανοίγματα.
	def home
		@cat_anoigmatos = OpenCategorie.all
	end

    ## Κρατάω ολες τις μεταβήτές που εχω ήδη πατήσει απο πριν με @.
    ## Διχνω ολα τα υλικά 
    ## Το σύμβολο ? ειναι για να δημιουργήσω url με το back button του browser.
    ## Έχω πρόβλημα με το back, κανει κατι ακαταλαβήστηκα.
    ## Η σελίδα αυτη χρησιμοποιεί τις μεθόδους kataskevastes, system, line και παίρνει δεδομένα απο αυτες σε json φορματ
	def material
		@open_categorie = params[:open_categorie]
        @uliko = Material.all
        @sumbol = "?"
	end

	def kataskevastes
		# 1 Constructor εχει πολλα materials, material_constructors ενδιάμεσος
		# Πατοντας στο υλικο ψαχνω τους κατασκεβαστες
		@kata = Constructor.joins(:material_constructors, :materials).where(["material_constructors.material_id = ? AND materials.id = ?", params[:material_id], params[:material_id]])
		#Κάνω join τους πινακες που θέλω και εχω στοιχεια πανω σε αυτον που θελω να παρω τις εγγραφες. 
		#Περνω τις εγγραφες με κοινα id 
		respond_to do |format|
          format.json { render json: @kata.to_json}
        end
	end

	def system
		##### ΛΑΘΟΣ 1 CONSTRUCTOR ΕΧΕΙ ΠΟΛΛΑ ΣΥΣΤΗΜΑΤΑ....ΘΑ ΓΙΝΕΙ ΟΠΩΣ ΑΠΟ ΚΑΤΩ ΠΟΥ ΨΑΧΝΩ ΤΑ ΠΟΛΛΑ ΚΑΙ ΟΧΙ ΤΟ 1
		@system = System.where(:constructor_id => params[:constructor_id])
		respond_to do |format|
          format.json { render json: @system.to_json}
        end
	end

	def line
		# 1 συστημα εχει πολλες γραμμες. Περνάω το id του συστηματος και το ψαννω στον ενδιάμεσο πινακα
		#Απλα εδω ψανχω τις γραμμες(τα πολλα) και οχι το συστημα(το 1) οπως πανω
		@line = Line.joins(:system_lines).where(["system_lines.system_id = ?", params[:system_id]])
		respond_to do |format|
          format.json { render json: @line.to_json}
        end
	end

    ## Η σελίδα αυτή εμφανίζει την επιλογή φύλλων.
    ## Κρατάω ολες τις μεταβήτές που εχω ήδη πατήσει απο πριν με @.
    ## Το σύμβολο ? ειναι για να δημιουργήσω url με το back button του browser.
    ## Έχω πρόβλημα με το back, κανει κατι ακαταλαβήστηκα.
	def leaf
		@sumbol = "?"
		@open_categorie_name = params[:open_categorie_name]
		@open_categorie = OpenCategorie.where(:name => params[:open_categorie_name]).first
		@material = Material.where(:id => params[:material_id]).first
		@constructor = Constructor.where(:id => params[:constructor_id]).first
		@system = System.where(:id => params[:system_id]).first
		@line = Line.where(:id => params[:line_id]).first
		####
		@leaf = Leaf.joins(:open_categorie_leafs).where(["open_categorie_leafs.open_categorie_id = ?", @open_categorie.id])
	end

    ## Σε αυτην την σελίδα προβάλω τους τύπους ανοίγματος.
    ## Αρχικα κάνω το join τα open_type με τα line 
    ## Και μετά απο αυτα που βρηκα διαλέγω αυτα με τα αντιστοιχα φυλλα και κατηγορια που διαλεξα. 
	def open_type
		@open_categorie = OpenCategorie.where(:name => params[:open_categorie_name]).first
		@material = Material.where(:name => params[:material_name]).first
		@constructor = Constructor.where(:name => params[:constructor_name]).first
		@system = System.where(:name => params[:system_name]).first
		@line = Line.where(:name => params[:line_name]).first
		@leaf = Leaf.where(:name => params[:leaf_name]).first
		##
		@open_type = OpenType.joins(:system_open_types).where(["system_open_types.line_id = ?", @line.id]).order(:order)
		@open_type1 = @open_type.where(:leaf_id => @leaf.id, :open_categorie_id => @open_categorie.id)
        
	end

    ## Εμφανίζω τα color ανάλωγα με την κατηγορία. Αυτη η σελίδα χρησιμοποιει και τις μεθοδους
    ## color_kasas και color_fulou. Αν αλλάξουν τα χρώματα απλα κάνω ενα νέο πινακα και συνδέω αυτον.
	def color
		@open_categorie = OpenCategorie.where(:name => params[:open_categorie_name]).first
		@material = Material.where(:name => params[:material_name]).first
		@constructor = Constructor.where(:name => params[:constructor_name]).first
		@system = System.where(:name => params[:system_name]).first
		@line = Line.where(:name => params[:line_name]).first
		@leaf = Leaf.where(:name => params[:leaf_name]).first
		@open_type = OpenType.where(:name => params[:open_type_name]).first
		##
		@colors_0 = Color.where(:katigoria => 0)
		@colors_standar = Color.where(:katigoria => 1)
		@colors_extra = Color.where(:katigoria => 2)
	end

	def corol_kasas
		@colors = Color.all
		respond_to do |format|
          format.json { render json: @colors.to_json}
        end
	end

	def color_fulou
		@colors = Color.all
		respond_to do |format|
          format.json { render json: @colors.to_json}
        end
	end

    ## Σε αυτην την σελίδα δίνω με @ ολες τις μεταβλητές που χρειάζονται στο πινακακι αριστερα.
    ## Ακόμη δίνω το max και min, width και height.
	def diastaseis
        @open_categorie = OpenCategorie.where(:name => params[:open_categorie_name]).first
		@material = Material.where(:name => params[:material_name]).first
		@constructor = Constructor.where(:name => params[:constructor_name]).first
		@system = System.where(:name => params[:system_name]).first
		@line = Line.where(:name => params[:line_name]).first
		@leaf = Leaf.where(:name => params[:leaf_name]).first
		@open_type = OpenType.where(:name => params[:open_type_name]).first
		@color = Color.where(:name => params[:color_name]).first
		@mesa_eksw = params[:mesa_eksw]
		##if params exists ΚΑΝΟΝΙΚΑ
		@color_deksia = Color.where(:name => params[:coldeksia]).first
		@color_aristera = Color.where(:name => params[:colaristera]).first
		@color_panw = Color.where(:name => params[:colpanw]).first
		@color_katw = Color.where(:name => params[:colkatw]).first
		@color_fulou = Color.where(:name => params[:colfullo]).first
		########
		@max_width = @open_type.max_width
		@min_width = @open_type.min_width
		@max_height = @open_type.max_height
		@min_height = @open_type.min_height
	end

    ## Η σελίδα extra προβάλει όλα τα extra που μπορει να πάρει ένα κούφωμα. 
    ## Αρχικά δίνω τα extra που θέλω.
    ## Μετά δίνω αυτα που πάτησα απο πρίν για το πινακάκι το κόκκινο.
    ## Η σελίδα αυτη χρισημοποιεί τις παρακάτω μεθόδους --->
    ## epikathimena, color_epikathimenou, eksoterika, color_eksoterikou, color_persidas, color_odoigou, tzamia, color_typos, color_profil.
    ## Όλες αυτές τις μεθόδους τις έχω για να πέρνω δεδομένα σε json format.
	def extra
		@epikathimena_cat = Epikathimeno.all
		@eksoteriko_cat = Eksoterika.all
		@persides = Persides.all
		@cat_tzamia = CatTzamia.all
		@typos = Profil.where(:width => 0)
		@profil = Profil.where.not(:width => 0)
		@roll_guide = RollGuide.all
		@order = Order.where(:id => params[:order]).first
		if !@order.nil?
			@order = Order.where(:id => params[:order]).first
		else
			@order = 0
		end
		if params.has_key?(:pse_user)
			#$pseUserId = params[:pse_user]
			session[:pseUserId] = params[:pse_user]
		end
		if params.has_key?(:paraggelia_id)
			#$paraggelia_simple = params[:paraggelia_id]
			session[:paraggelia_simple] = params[:paraggelia_id]
			session[:dealer_id] = params[:dealer_id]
		end

        ##Κοκκινο πινακάκι
		@open_categorie = OpenCategorie.where(:name => params[:open_categorie_name]).first
		@material = Material.where(:name => params[:material_name]).first
		@constructor = Constructor.where(:name => params[:constructor_name]).first
		@system = System.where(:name => params[:system_name]).first
		@line = Line.where(:name => params[:line_name]).first
		@leaf = Leaf.where(:name => params[:leaf_name]).first
		@open_type = OpenType.where(:name => params[:open_type_name]).first
		@color = Color.where(:name => params[:color_name]).first
		@mesa_eksw = params[:mesa_eksw]
		@xwrisma1 = params[:xwrisma1]
		@xwrisma2 = params[:xwrisma2]
		@xwrisma3_1 = params[:xwrisma3_1]
		@xwrisma3_2 = params[:xwrisma3_2]

app/views/etic/_header.html.erb
<div class="header_logo">
  <%= image_tag("Etik_logo_header.jpg", size: "1170x198", class: "logo") %>
</div>
<nav class="navbar navbar-default" role="navigation" style="margin: auto;">
  <div class="container header_con">
    <!-- Brand and toggle get grouped for better mobile display -->
    <!--
    <div class="navbar-header">
      <button type="button" class="navbar-toggle /*collapsed*/" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Etik</a>
    </div>
  -->

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="/*collapse navbar-collapse*/" id="/*bs-example-navbar-collapse-1*/">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <% if current_user.admin === nil %>
            <% if false %><!---->
            <li><a href="<%= etic_home_path %>?pse_user=0">Application <span class="sr-only">(current)</span></a>
            </li>
            <% end %><!---->
          <% end %>
        <% end %>
        <li><a href="<%= etic_contact_path %>">Contact</a></li>
        <li class="lang">
            <div class="btn-group btn-group-xs" role="group" aria-label="...">
              <%= link_to "English",etic_language_path(:lang => "en") %>
              <%= link_to "Greek",etic_language_path(:lang => "gr") %>
              <%= link_to "German",etic_language_path(:lang => "de") %>
            </div>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
         <% if user_signed_in? %>
         <% if current_user.admin == 1 %> <!--Mesa giati vgazei error-->
           <li><a href="<%= etic_etic_card_path %>">Admin panel</a>
           <li><a href="<%= etic_history_admin_path %>">History</a></li>
         <% else %>
           <li><a href="<%= etic_user_diax_path %>">Offers</a></li>
           <li><a href="<%= etic_history_path %>">History</a></li>
         <% end %>
         <% end %>
         <% if user_signed_in? %>
          <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li> 
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
        <% else %>
          <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li>
          <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
        <% end %>
      </ul>
      </br></br>
        <p class="katw_mpara">Hello <strong><%= current_user.name %> </strong> </p>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/etic/_header_app.html.erb
<nav class="navbar navbar-default" role="navigation" style="margin: auto;">
  <div class="container header_con">
    <!-- Brand and toggle get grouped for better mobile display -->
    <!--
    <div class="navbar-header">
      <button type="button" class="navbar-toggle /*collapsed*/" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Etik</a>
    </div>
  -->

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="/*collapse navbar-collapse*/" id="/*bs-example-navbar-collapse-1*/">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <% if current_user.admin === nil %>
            <% if false %><!---->
            <li><a href="<%= etic_home_path %>?pse_user=0">Application <span class="sr-only">(current)</span></a>
            </li>
            <% end %><!---->
          <% end %>
        <% end %>
        <li><a href="<%= etic_contact_path %>">Contact</a></li>
        <li class="lang">
            <div class="btn-group btn-group-xs" role="group" aria-label="...">
              <%= link_to "English",etic_language_path(:lang => "en") %>
              <%= link_to "Greek",etic_language_path(:lang => "gr") %>
              <%= link_to "German",etic_language_path(:lang => "de") %>
            </div>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
         <% if user_signed_in? %>
         <% if current_user.admin == 1 %> <!--Mesa giati vgazei error-->
           <li><a href="<%= etic_etic_card_path %>">Admin panel</a>
           <li><a href="<%= etic_history_admin_path %>">History</a></li>
         <% else %>
           <li><a href="<%= etic_user_diax_path %>">Offers</a></li>
           <li><a href="<%= etic_history_path %>">History</a></li>
         <% end %>
         <% end %>
         <% if user_signed_in? %>
          <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li> 
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
        <% else %>
          <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li>
          <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
        <% end %>
      </ul>
      </br></br>
        <p class="katw_mpara">Hello <strong><%= current_user.name %> </strong> </p>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/etic/etic_card.html.erb
<div class="container con_home">
  <div class="">

        <%= link_to "Νέα παραγγελία", etic_new_user_path ,class: "btn btn-primary" %>
        <%= link_to "DataBase", etic_new_user_path ,class: "btn btn-primary" %>

      </div>
  <div class="row row_admin">

    <div class="admin_main">

    <h1>Orders</h1>

    <div class="by_mult">Order by:</div>
    
    <select class="select" id="select" multiple="multiple" size="8">
      <option value="code_low">code: Low to High</option>
      <option value="code_high">code: High to Low</option>
      <option value="name_a">name: A to Z</option>
      <option value="name_z">name: Z to A</option>
      <option value="date_new">date: New to Old</option>
      <option value="date_old">date: Old to New</option>
      <option value="price_high">price: High to Low</option>
      <option value="price_low">price: Low to High</option>
    </select>

    <div class="by_mult">Order by:</div>

    <select class="select2" id="cust" multiple="multiple" size="8">
      <option value="0">All</option>
      <% @customers.each do |c| %>
      <option value="<%= c.id %>"><%= c.id %> - <%= c.eponimo %> <%= c.name %>, <%= c.company %>  </option>
      <% end %>
    </select>

    <%= form_tag etic_etic_card_path, :method => 'get' do %>
      <p>
        <%= text_field_tag :search, params[:search] %>
        <%= submit_tag "Search", :name => nil %>
        <%= submit_tag "all", :name => "all" %>
      </p>
    <% end %>

   
      <div class="table-responsive">
          <div class="pdf" id="pdf">
            <table class="table table_card table_grammata_diax">

            <thead>
              <tr class="root">
                <th id="kartoula_head">code</th>
                <th id="kartoula_head">Dealer</th>
                <th id="kartoula_head">Customer</th> 
                <th id="kartoula_head">Date</th>
                <th id="kartoula_head">Number of windows</th> 
                <th id="kartoula_head">total price</th>
                <th id="kartoula_head">card</th>
                <th id="kartoula_head">+</th>
                
              </tr>
            </thead>

            <tbody>
              <% if (!@paraggelies.nil?) %>
              <% @paraggelies.each do |par| %>
                <tr class="root">
                  <% customer =  SimpleUserPse.where(:id => par.customer).first %>
                  <% admin =  User.where(:id => par.user).first %>
                  <% num_of_window =  Order.where(:paraggelia_id => par.id).count %> <!--Αριθμος κουφωματων χωρις την ποσοτητα-->
                  <% order =  Order.where(:paraggelia_id => par.id).all %>
                  <% sunolo = 0; %>
                      <% kouf = 0 %>
                        <% order.each do |i| %>
                        <% sunolo = sunolo + i.price_sum %>
                        <% kouf = kouf + i.posotoita %>
                     <% end %>
                  <td><%= par.id %></td> 
                  <td><%= admin.name %></td> 
                  <td><%= customer.eponimo %> <%= customer.name %></td>
                  <td><%= par.created_at.strftime("%d %b %y %H:%M:%S") %></td>
                  <td style="text-align:center"><%= kouf %></td>
                  <td><%= number_with_precision(sunolo, :precision => 2) %> €</td>
                  <td><button type="button" class="btn btn-default card" id="<%= par.id %>">Card </button></td>
                  <td><%= link_to "+", etic_simple_pse_user_path(:paraggelia_id => par.id, :dealer => admin.id) ,class: "btn btn-primary", id: par.id %></td>
                  
                </tr>
              <% end %>
              <% end %>
            </tbody>
          </table>


      </div><!--div gia table-->
    </div><!--div gia table-->


      </div> <!--admin main-->

  </div><!--row-->

  <div class="row">
    <h1>Pseudo Users</h1>
    
    <div class="admin_main">
    <% if (!@pseudo.nil?) %>
          <% @pseudo.each do |user| %>
          <!--Υπολογισμοι για καθε user
            1. Ποσα κουφωματα εχει κανει
            2. Την παραγγελια του
            3. Με each το συνολο τησ παραγγελιας του
          -->
          <% num_of_window =  Order.where(:user_id => user.id).where(:pse => 1).count %>
          <% user_order =  Order.where(:user_id => user.id).where(:pse => 1).all %>
          <% sunolo = 0; %>
          <% kouf = 0 %>
            <% user_order.each do |i| %>
            <% sunolo = sunolo + i.price_sum %>
            <% kouf = kouf + i.posotoita %>
         <% end %>
         <!-- end υπολογισμων -->

            <div class="admin_pse_user" id="<%= user.id %>">
              <div class="user_id" style="display:none;"><%= user.id %></div>
              <b>Name:</b> <%= user.name %><br>
              <b>Surname:</b> <%= user.eponimo %><br>
              <b>Phone:</b> <%= user.phone %><br>
              <b>Address:</b> <%= user.address %><br>
              <b>Company:</b> <%= user.company %><br>
              <b>Email:</b> <%= user.email %><br>
              <b>Number of windows:</b> <%= kouf %><br>
              <b>Total Price:</b> <%= number_with_precision(sunolo, :precision => 2) %> €<br>
              <%= link_to "+", etic_pse_user_path(:pse_user => user.id) ,class: "btn btn-primary" %>
              <button type="button" class="btn btn-default card" id="<%= user.id %>">Card</button>
              <%= link_to "Done", etic_pse_done_path(:pse_user => user.id, :done => 1) ,class: "btn btn-success done" %>
              <%= link_to "No Done", etic_pse_done_path(:pse_user => user.id, :done => 0) ,class: "btn btn-primary done" %>
              <% if (user.done == 1) %>
                <div class="hidden" id="<%= user.id %>"></div>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>

  </div>

</div>

<script>
$(document).ready(function(){

  a = $('.hidden');
  a.each(function(){
    b = $(this).attr('id');
    //$("#"+b+"").css("background-color","#5cb85c");
    $("#"+b+"").css("border-color","#5cb85c");
    $("#"+b+"").css("border-width","5px");
    //alert(b);
  });

  
  $(".card_user").click(function(){
    id = $(this).attr('id');
    window.location.href = "<%= etic_etic_user_card_path %>?id="+id+""
  });

  $(".card").click(function(){
    id = $(this).attr('id');
    window.location.href = "<%= etic_simple_pse_user_card_path %>?id="+id+""
  });


}); //ready end
</script>

app/views/etic/home.html.erb
<!--<div id="loading"></div>-->
<div class="container con_home">
  <div class="row row_home">
  	<div class="col-xs-4">
      
      <button class="menu hidden-lg hidden-sm hidden-md" onclick="toggle()">
        <span class="glyphicon glyphicon-home"></span>
      </button>
    
      <ul class="ul">
        <li class="li1"><a href="/etic/home/"  class="li1">1 | <%= t 'mpara.open_category' %></a></li>
        <li>2 | <%= t 'mpara.material' %></li>
        <li>3 | <%= t 'mpara.leaf' %></li>
        <li>4 | <%= t 'mpara.open_type' %></li>
        <li>5 | <%= t 'mpara.color' %></li>
        <li>6 | <%= t 'mpara.dimension' %></li>
        <li>7 | <%= t 'mpara.price' %></li>
        <%= @pseUser %>
      </ul>

  	</div>
  	<div class="col-xs-7 home_div">
      <h2>1. <%= t 'home.title' %></h2>

      <div class="gen_info"> 
        <p class="gen_p_info">Γενικες οδηγίες για την επιλογη παραθύρων!!! Σε αυτό το πλαίσιο μπορούμε να προσθέσουμε οποιαδήποτε πληροφορία θέλουμε.</p>
      </div>

  		<% @cat_anoigmatos.each do |c| %>
  		<div class="cat_anoigmatos" id="<%= c.name %>">
        <h5 class="anoigma_name"><%= t "kouf."<<c.name %></h5> <!--c.name-->
  		  <%= link_to image_tag(c.image), etic_material_path(:open_categorie => c.name) %>
        <div class="home_info">
          <p class="p_home">Κάτι Κάτι Κάτι Κάτι Κάτι Κάτι Κάτι Κάτι Κάτι Κάτι Κάτι Κάτι Κάτι Κάτι Κάτι Κάτι</p>
        </div>
      </div>
  		<% end %>
  	</div>
  </div>
</div>

<!--
<script>

  $(document).ready(function(){

  $(".ul").hide();

  $( ".menu" ).mouseenter(function() {
    $(".ul").fadeToggle(1000);
  });


  });

  function toggle() {
    $(".ul").fadeToggle(1000);
  }

</script>

<script>

$(document).ready(function(){
	$(".cat_anoigmatos").click(function(){
		alert( $(this).attr('id') );
	    $.ajax({
	          type:'POST',
	          url:'/etic/material',
	          dataType: "json",
	          data: { open_categorie: $(this).attr('id') },
	          success: function(data) { 
	            },
	          error: function(data) { 
	            }
	        });//end ejax
	});//end click
});//end ready

</script>
-->